name: Lint Code

on:
  push:
     branches:
      - '*'
  pull_request:
     branches:
      - '*'

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3    

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22'

            - name: Install dependencies
              run: |
                cd candlelight.client
                npm install

            - name: Run ESLint
              run: |
                cd candlelight.client
                npm run lint
            - name: Run tests
              run: |
                cd candlelight.client
                npm run test
