name: Tests - Backend

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test Candlelight.Api.Tests/Candlelight.Api.Tests.csproj --no-build --configuration Release --logger trx